# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: railsim.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrailsim.proto\"L\n\x0bObservation\x12\x0f\n\x07obsTree\x18\x01 \x03(\x01\x12\x12\n\ntrainState\x18\x02 \x03(\x01\x12\x18\n\x10positionNextNode\x18\x03 \x03(\x01\"n\n\tActionMap\x12.\n\ndictAction\x18\x01 \x03(\x0b\x32\x1a.ActionMap.DictActionEntry\x1a\x31\n\x0f\x44ictActionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x95\x01\n\x0eObservationMap\x12=\n\x0f\x64ictObservation\x18\x01 \x03(\x0b\x32$.ObservationMap.DictObservationEntry\x1a\x44\n\x14\x44ictObservationEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.Observation:\x02\x38\x01\"#\n\x14\x43onfirmationResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t\"\x1c\n\x08GrpcPort\x12\x10\n\x08grpcPort\x18\x01 \x01(\x05\x32w\n\x10RailsimConnecter\x12*\n\tgetAction\x12\x0f.ObservationMap\x1a\n.ActionMap\"\x00\x12\x37\n\x0bupdateState\x12\x0f.ObservationMap\x1a\x15.ConfirmationResponse\"\x00\x32v\n\x0eRailsimFactory\x12\x34\n\x0egetEnvironment\x12\t.GrpcPort\x1a\x15.ConfirmationResponse\"\x00\x12.\n\x08resetEnv\x12\t.GrpcPort\x1a\x15.ConfirmationResponse\"\x00\x42\x17\n\x13railsim_dummy.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'railsim_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023railsim_dummy.protoP\001'
  _globals['_ACTIONMAP_DICTACTIONENTRY']._options = None
  _globals['_ACTIONMAP_DICTACTIONENTRY']._serialized_options = b'8\001'
  _globals['_OBSERVATIONMAP_DICTOBSERVATIONENTRY']._options = None
  _globals['_OBSERVATIONMAP_DICTOBSERVATIONENTRY']._serialized_options = b'8\001'
  _globals['_OBSERVATION']._serialized_start=17
  _globals['_OBSERVATION']._serialized_end=93
  _globals['_ACTIONMAP']._serialized_start=95
  _globals['_ACTIONMAP']._serialized_end=205
  _globals['_ACTIONMAP_DICTACTIONENTRY']._serialized_start=156
  _globals['_ACTIONMAP_DICTACTIONENTRY']._serialized_end=205
  _globals['_OBSERVATIONMAP']._serialized_start=208
  _globals['_OBSERVATIONMAP']._serialized_end=357
  _globals['_OBSERVATIONMAP_DICTOBSERVATIONENTRY']._serialized_start=289
  _globals['_OBSERVATIONMAP_DICTOBSERVATIONENTRY']._serialized_end=357
  _globals['_CONFIRMATIONRESPONSE']._serialized_start=359
  _globals['_CONFIRMATIONRESPONSE']._serialized_end=394
  _globals['_GRPCPORT']._serialized_start=396
  _globals['_GRPCPORT']._serialized_end=424
  _globals['_RAILSIMCONNECTER']._serialized_start=426
  _globals['_RAILSIMCONNECTER']._serialized_end=545
  _globals['_RAILSIMFACTORY']._serialized_start=547
  _globals['_RAILSIMFACTORY']._serialized_end=665
# @@protoc_insertion_point(module_scope)
